apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-secret-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-secret-world
        app: hello-secret-world
    spec:
      hostname: hello-secret-world
      containers:
      - name: hello-secret-world
        image: danielsomerfield/hello-secret-world
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hello-secret-world
  labels:
    run: hello-secret-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    run: hello-secret-world